### ISSUE TITLE
NullPointerException when reading arkprofile and a possible fix (PrimalPlayerData was renamed).

### ISSUE THREAD

**Issue by Kakoen** [Qowyn/ark-savegame-toolkit#1]
Starting from patch 257.0, it seems like Ark renamed its PrimalPlayerData object, resulting in a null profile when reading .arkprofile files. It was renamed to PrimalPlayerDataBP_C

In ArkProfile.java:77 there is a check on class name, 

      if (object.getClassString().equals("PrimalPlayerData")) {
        profile = object;
      }

For me it's fixed when I change it to:

      if (object.getClassString().equals("PrimalPlayerData") || object.getClassString().equals("PrimalPlayerDataBP_C")) {
        profile = object;
      }

I accept both to remain backwards compatible with older profiles. Profiles only get updated when someone logs on.

Hope it helps anyone using this awesome library!

**Comment by cokll** [comment]
Thx
