### ISSUE TITLE
Dino levels represented...interestingly.

### ISSUE THREAD

**Issue by Letoric** [Qowyn/ark-savegame-toolkit#2]
Hi Qowyn. Love what you've done here. I wanted to present an issue that you may already be aware of, regarding higher level dinos. Your tool is reporting some stats as a negative value for the levels in them. Here are a couple snaps:
[
    {
        "x":157322.6875,
        "y":-280067.4375,
        "z":-11064.4912109375,
        "lat":15.0,
        "lon":69.7,
        "id":1077986394594013586,
        "tamed":true,
        "team":1384325564,
        "color0":14,
        "color2":14,
        "color4":23,
        "color5":27,
        "tamedAtTime":219178.6412339434,
        "tamedTime":427218.4212660566,
        "tribe":"Masters of the Universe",
        "tamer":"Masters of the Universe",
        "baseLevel":1007,
        "wildLevels":{
            "health":-78,
            "stamina":-82,
            "food":-89,
            "weight":-94,
            "melee":-85,
            "speed":-102
        },
        "fullLevel":1207,
        "tamedLevels":{
            "health":46,
            "melee":-126,
            "speed":24
        },
        "experience":1083787.75
    },
    {
        "x":156987.890625,
        "y":-280804.65625,
        "z":-10840.4287109375,
        "lat":14.9,
        "lon":69.6,
        "id":1645493759220551812,
        "tamed":true,
        "team":1384325564,
        "female":true,
        "color0":19,
        "color2":19,
        "color4":28,
        "color5":29,
        "tribe":"Masters of the Universe",
        "tamer":"Masters of the Universe",
        "name":"7th DRGN of the 7th DRGN",
        "baseLevel":1165,
        "wildLevels":{
            "health":-59,
            "stamina":-56,
            "food":-65,
            "weight":-64,
            "melee":-56,
            "speed":-72
        },
        "fullLevel":1365,
        "tamedLevels":{
            "health":31,
            "melee":-87
        },
        "experience":1.2463515E7
    },
    {
        "x":155366.71875,
        "y":-281359.0,
        "z":-10874.7412109375,
        "lat":14.8,
        "lon":69.4,
        "id":1861908537070598845,
        "tamed":true,
        "team":1384325564,
        "color0":14,
        "color2":14,
        "color4":28,
        "color5":27,
        "tamedAtTime":643607.8628289737,
        "tamedTime":2789.1996710263193,
        "tribe":"Masters of the Universe",
        "imprinter":"Letoric",
        "baseLevel":1063,
        "wildLevels":{
            "health":-78,
            "stamina":-56,
            "food":-89,
            "weight":-64,
            "melee":-85,
            "speed":-102
        }
    },
    {
        "x":155571.609375,
        "y":-281297.90625,
        "z":-10900.8984375,
        "lat":14.8,
        "lon":69.4,
        "id":739668277274827871,
        "tamed":true,
        "team":1384325564,
        "color0":19,
        "color2":19,
        "color4":23,
        "color5":29,
        "tamedAtTime":644981.7407703251,
        "tamedTime":1415.3217296749353,
        "tribe":"Masters of the Universe",
        "imprinter":"Letoric",
        "baseLevel":1106,
        "wildLevels":{
            "health":-59,
            "stamina":-56,
            "food":-65,
            "weight":-94,
            "melee":-85,
            "speed":-72
        }
    },
    {
        "x":155552.3125,
        "y":-281499.8125,
        "z":-10862.3896484375,
        "lat":14.8,
        "lon":69.4,
        "id":1374381456186734312,
        "tamed":true,
        "team":1384325564,
        "color0":14,
        "color2":14,
        "color4":23,
        "color5":27,
        "tamedAtTime":646286.7964395136,
        "tamedTime":110.26606048643589,
        "tribe":"Masters of the Universe",
        "imprinter":"Letoric",
        "baseLevel":1036,
        "wildLevels":{
            "health":-78,
            "stamina":-82,
            "food":-89,
            "weight":-94,
            "melee":-56,
            "speed":-102
        }
    }
]

As you can see, several values have negative values. These are not stats that exceed the 255 levels in a stat, they persist through reboots. They are high level, as you can see. Is there any other information I can provide you to help you diagnose/resolve this?

Thanks!

**Comment by Letoric** [comment]
Apologies, this is for ark-tools. If you're able to move it, that would be great.

**Comment by Qowyn** [comment]
Should be fixed with the new release of ark-tools. Thanks for reporting!
