### ISSUE TITLE
Error while reading world files for modded maps

### ISSUE THREAD

**Issue by Letoric** [Qowyn/ark-savegame-toolkit#3]
I'm seeing this lately for some of my modded maps. 
java.lang.UnsupportedOperationException: Found unexpected Value 2 at 1438
        at qowyn.ark.ArkSavegame.readBinary(ArkSavegame.java:145)
        at qowyn.ark.ArkSavegame.<init>(ArkSavegame.java:78)
        at qowyn.ark.tools.CreatureListCommands.listImpl(CreatureListCommands.java:109)
        at qowyn.ark.tools.CreatureListCommands.wild(CreatureListCommands.java:67)
        at qowyn.ark.tools.App.main(App.java:114)

It was working for the world, however, after a wild dino wipe, it stopped working, and still continues to not work even after players have logged into the world and the world has been re-launched and saved to see if it helps.

Here's the command arguments used:
wild <pathtoservers>\ark-3\ShooterGame\Saved\SavedArks\ShigoIslands.ark <pathtowebsite>\Wild\ark-3\ -p --pretty-printing

Attached is one of the world files exhibiting the issue. Hope it helps.

[ShigoIslands.zip](https://github.com/Qowyn/ark-savegame-toolkit/files/1050738/ShigoIslands.zip)

**Comment by Letoric** [comment]
Apologies, this is for Ark-Tools, not ark-savegame-toolkit. If you're able to move it to that issue tracker, that would be good :)

**Comment by Qowyn** [comment]
Thats actually been a bug in ark-savegame-tookit :) and it's now fixed with the new releases of both.
